[package]
name = "tda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tda"
crate-type = ["cdylib"]

[dependencies]
hashbrown = "0.14.3"
human-repr = "1.1.0"
pyo3 = "0.18.1"
rayon = "1.8.1"
