[package]
name = "tda_core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tda_core"

[dependencies]
thiserror = "2.0.18"
rayon = "1.11"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "persistent_homology"
harness = false
